import type { Epoca } from "@/components/ui/Retrato";

/** Metadata estructurada por slug: complementa el copy editorial en registro.ts */
export type TaxonomiaCronica = {
  epoca: Epoca;
  categorias: string[];
  anioInicio: number;
  anioFin: number;
  numero?: number;
  destacada?: boolean;
  orden?: number;
};

export const taxonomiaPorSlug: Record<string, TaxonomiaCronica> = {
  "el-cruce-de-los-andes": {
    epoca: "independencia",
    categorias: ["independencia", "batallas"],
    anioInicio: 1817,
    anioFin: 1817,
    numero: 1,
    destacada: true,
    orden: 1,
  },
  "la-ciudad-que-vencio-a-un-imperio": {
    epoca: "colonia",
    categorias: ["batallas", "independencia"],
    anioInicio: 1806,
    anioFin: 1807,
    numero: 2,
    orden: 1,
  },
  "las-48-horas-de-mayo": {
    epoca: "independencia",
    categorias: ["politica", "independencia"],
    anioInicio: 1810,
    anioFin: 1810,
    orden: 1,
  },
  "el-exodo-jujeno": {
    epoca: "independencia",
    categorias: ["batallas", "independencia"],
    anioInicio: 1812,
    anioFin: 1812,
    orden: 2,
  },
  "la-guerra-gaucha": {
    epoca: "independencia",
    categorias: ["guerras", "batallas"],
    anioInicio: 1815,
    anioFin: 1821,
    orden: 3,
  },
  "juana-azurduy": {
    epoca: "independencia",
    categorias: ["personajes", "batallas"],
    anioInicio: 1810,
    anioFin: 1825,
    orden: 4,
  },
  "el-9-de-julio": {
    epoca: "independencia",
    categorias: ["politica", "independencia"],
    anioInicio: 1816,
    anioFin: 1816,
    numero: 5,
    destacada: true,
    orden: 5,
  },
  caseros: {
    epoca: "organizacion",
    categorias: ["batallas", "politica"],
    anioInicio: 1852,
    anioFin: 1852,
    numero: 6,
    orden: 1,
  },
  "el-17-de-octubre": {
    epoca: "moderna",
    categorias: ["politica", "sociedad"],
    anioInicio: 1945,
    anioFin: 1945,
    orden: 1,
  },
  "la-vuelta-de-obligado": {
    epoca: "organizacion",
    categorias: ["batallas", "guerras"],
    anioInicio: 1845,
    anioFin: 1845,
    numero: 8,
    orden: 2,
  },
  "la-batalla-de-tucuman": {
    epoca: "independencia",
    categorias: ["batallas", "independencia"],
    anioInicio: 1812,
    anioFin: 1812,
    numero: 9,
    orden: 6,
  },
  evita: {
    epoca: "moderna",
    categorias: ["politica", "personajes"],
    anioInicio: 1945,
    anioFin: 1952,
    numero: 10,
    orden: 2,
  },
  "setenta-y-cuatro-dias": {
    epoca: "contemporanea",
    categorias: ["guerras", "memoria"],
    anioInicio: 1982,
    anioFin: 1982,
    numero: 11,
    destacada: true,
    orden: 1,
  },
  "nunca-mas": {
    epoca: "contemporanea",
    categorias: ["memoria", "politica"],
    anioInicio: 1976,
    anioFin: 1983,
    orden: 2,
  },
  "la-batalla-de-salta": {
    epoca: "independencia",
    categorias: ["batallas", "independencia"],
    anioInicio: 1813,
    anioFin: 1813,
    numero: 13,
    orden: 7,
  },
  "san-lorenzo": {
    epoca: "independencia",
    categorias: ["batallas", "independencia"],
    anioInicio: 1813,
    anioFin: 1813,
    orden: 8,
  },
  "barranca-yaco": {
    epoca: "organizacion",
    categorias: ["politica", "tragedias"],
    anioInicio: 1835,
    anioFin: 1835,
    numero: 15,
    orden: 3,
  },
  "el-primer-golpe": {
    epoca: "moderna",
    categorias: ["politica"],
    anioInicio: 1930,
    anioFin: 1930,
    numero: 16,
    orden: 3,
  },
  "la-constitucion-de-1853": {
    epoca: "organizacion",
    categorias: ["politica"],
    anioInicio: 1853,
    anioFin: 1853,
    orden: 4,
  },
  chacabuco: {
    epoca: "independencia",
    categorias: ["batallas", "independencia"],
    anioInicio: 1817,
    anioFin: 1817,
    orden: 9,
  },
  maipu: {
    epoca: "independencia",
    categorias: ["batallas", "independencia"],
    anioInicio: 1818,
    anioFin: 1818,
    orden: 10,
  },
  pavon: {
    epoca: "organizacion",
    categorias: ["batallas", "politica"],
    anioInicio: 1859,
    anioFin: 1859,
    orden: 5,
  },
  "la-revolucion-libertadora": {
    epoca: "moderna",
    categorias: ["politica", "guerras"],
    anioInicio: 1955,
    anioFin: 1955,
    orden: 4,
  },
  "el-cordobazo": {
    epoca: "contemporanea",
    categorias: ["sociedad", "politica"],
    anioInicio: 1969,
    anioFin: 1969,
    orden: 3,
  },
  guayaquil: {
    epoca: "independencia",
    categorias: ["politica", "independencia"],
    anioInicio: 1822,
    anioFin: 1822,
    orden: 11,
  },
  "el-facundo": {
    epoca: "organizacion",
    categorias: ["cultura", "politica"],
    anioInicio: 1845,
    anioFin: 1845,
    numero: 17,
    orden: 6,
  },
  "malvinas-ciudad": {
    epoca: "contemporanea",
    categorias: ["guerras", "memoria", "sociedad"],
    anioInicio: 1982,
    anioFin: 1982,
    numero: 18,
    orden: 4,
  },
  "la-conquista-del-desierto": {
    epoca: "moderna",
    categorias: ["guerras", "politica"],
    anioInicio: 1878,
    anioFin: 1885,
    orden: 5,
  },
  rivadavia: {
    epoca: "organizacion",
    categorias: ["politica"],
    anioInicio: 1826,
    anioFin: 1827,
    numero: 19,
    orden: 7,
  },
  junin: {
    epoca: "independencia",
    categorias: ["batallas", "independencia"],
    anioInicio: 1824,
    anioFin: 1824,
    orden: 12,
  },
  moreno: {
    epoca: "independencia",
    categorias: ["politica", "cultura"],
    anioInicio: 1810,
    anioFin: 1811,
    orden: 2,
  },
  "semana-tragica": {
    epoca: "moderna",
    categorias: ["sociedad", "politica"],
    anioInicio: 1919,
    anioFin: 1919,
    numero: 20,
    orden: 6,
  },
  federalizacion: {
    epoca: "organizacion",
    categorias: ["politica"],
    anioInicio: 1880,
    anioFin: 1880,
    numero: 21,
    orden: 8,
  },
  "el-2001": {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 2001,
    anioFin: 2002,
    numero: 22,
    orden: 5,
  },
  ayacucho: {
    epoca: "independencia",
    categorias: ["batallas", "independencia"],
    anioInicio: 1824,
    anioFin: 1824,
    orden: 13,
  },
  dorrego: {
    epoca: "organizacion",
    categorias: ["politica", "guerras"],
    anioInicio: 1827,
    anioFin: 1828,
    orden: 2,
  },
  rosas: {
    epoca: "organizacion",
    categorias: ["politica", "guerras"],
    anioInicio: 1835,
    anioFin: 1852,
    numero: 23,
    destacada: true,
    orden: 3,
  },
  mitre: {
    epoca: "organizacion",
    categorias: ["politica", "guerras", "cultura"],
    anioInicio: 1852,
    anioFin: 1870,
    numero: 24,
    orden: 9,
  },
  "ley-saenz-pena": {
    epoca: "moderna",
    categorias: ["politica"],
    anioInicio: 1912,
    anioFin: 1916,
    numero: 25,
    orden: 7,
  },
  alberdi: {
    epoca: "organizacion",
    categorias: ["politica", "cultura"],
    anioInicio: 1852,
    anioFin: 1853,
    orden: 10,
  },
  "patagonia-rebelde": {
    epoca: "moderna",
    categorias: ["sociedad", "politica"],
    anioInicio: 1920,
    anioFin: 1922,
    orden: 8,
  },
  ituzaingo: {
    epoca: "organizacion",
    categorias: ["batallas", "guerras"],
    anioInicio: 1827,
    anioFin: 1827,
    numero: 26,
    orden: 4,
  },
  "la-transicion": {
    epoca: "contemporanea",
    categorias: ["politica", "memoria"],
    anioInicio: 1983,
    anioFin: 1985,
    numero: 27,
    destacada: true,
    orden: 6,
  },
  urquiza: {
    epoca: "organizacion",
    categorias: ["politica", "batallas"],
    anioInicio: 1851,
    anioFin: 1852,
    numero: 28,
    orden: 5,
  },
  castelli: {
    epoca: "independencia",
    categorias: ["politica", "batallas", "independencia"],
    anioInicio: 1810,
    anioFin: 1811,
    orden: 3,
  },
  guemes: {
    epoca: "independencia",
    categorias: ["guerras", "batallas"],
    anioInicio: 1815,
    anioFin: 1821,
    orden: 4,
  },
  "la-bandera": {
    epoca: "independencia",
    categorias: ["independencia", "cultura"],
    anioInicio: 1812,
    anioFin: 1812,
    numero: 29,
    destacada: true,
    orden: 6,
  },
  saavedra: {
    epoca: "independencia",
    categorias: ["politica", "independencia"],
    anioInicio: 1810,
    anioFin: 1810,
    numero: 30,
    orden: 1,
  },
  "la-convertibilidad": {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1991,
    anioFin: 2002,
    numero: 31,
    orden: 7,
  },
  mariquita: {
    epoca: "independencia",
    categorias: ["personajes", "politica"],
    anioInicio: 1786,
    anioFin: 1868,
    orden: 2,
  },
  liniers: {
    epoca: "colonia",
    categorias: ["personajes", "batallas"],
    anioInicio: 1806,
    anioFin: 1810,
    orden: 2,
  },
  sarmiento: {
    epoca: "organizacion",
    categorias: ["personajes", "politica"],
    anioInicio: 1811,
    anioFin: 1888,
    numero: 32,
    destacada: true,
    orden: 8,
  },
  yrigoyen: {
    epoca: "moderna",
    categorias: ["politica", "personajes"],
    anioInicio: 1916,
    anioFin: 1930,
    numero: 33,
    orden: 8,
  },
  paraguay: {
    epoca: "organizacion",
    categorias: ["guerras", "batallas"],
    anioInicio: 1865,
    anioFin: 1870,
    numero: 34,
    orden: 9,
  },
  roca: {
    epoca: "organizacion",
    categorias: ["personajes", "politica"],
    anioInicio: 1843,
    anioFin: 1914,
    numero: 35,
    destacada: true,
    orden: 10,
  },
  belgrano: {
    epoca: "independencia",
    categorias: ["personajes", "independencia"],
    anioInicio: 1770,
    anioFin: 1820,
    numero: 36,
    destacada: true,
    orden: 7,
  },
  huaqui: {
    epoca: "independencia",
    categorias: ["batallas", "independencia"],
    anioInicio: 1811,
    anioFin: 1811,
    numero: 37,
    orden: 5,
  },
  peron: {
    epoca: "contemporanea",
    categorias: ["politica", "personajes"],
    anioInicio: 1943,
    anioFin: 1974,
    orden: 3,
  },
  alfonsin: {
    epoca: "contemporanea",
    categorias: ["politica", "memoria"],
    anioInicio: 1983,
    anioFin: 1989,
    orden: 4,
  },
  "el-43": {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1943,
    anioFin: 1945,
    numero: 38,
    destacada: true,
    orden: 8,
  },
  "voto-femenino": {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1947,
    anioFin: 1947,
    numero: 39,
    orden: 9,
  },
  menem: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1989,
    anioFin: 1999,
    numero: 40,
    orden: 10,
  },
  ongania: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1966,
    anioFin: 1970,
    orden: 5,
  },
  hiperinflacion: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1989,
    anioFin: 1990,
    orden: 6,
  },
  "el-retorno": {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1972,
    anioFin: 1974,
    numero: 41,
    orden: 11,
  },
  "las-madres": {
    epoca: "contemporanea",
    categorias: ["memoria", "sociedad"],
    anioInicio: 1977,
    anioFin: 1983,
    numero: 42,
    destacada: true,
    orden: 12,
  },
  kirchner: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 2003,
    anioFin: 2010,
    numero: 43,
    orden: 13,
  },
  "el-proceso": {
    epoca: "contemporanea",
    categorias: ["memoria", "politica"],
    anioInicio: 1976,
    anioFin: 1983,
    orden: 7,
  },
  montoneros: {
    epoca: "contemporanea",
    categorias: ["politica", "guerras"],
    anioInicio: 1970,
    anioFin: 1976,
    orden: 8,
  },
  frondizi: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1958,
    anioFin: 1962,
    numero: 44,
    orden: 4,
  },
  illia: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1963,
    anioFin: 1966,
    numero: 45,
    orden: 5,
  },
  cristina: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 2007,
    anioFin: 2015,
    numero: 46,
    orden: 14,
  },
  "triple-a": {
    epoca: "contemporanea",
    categorias: ["memoria", "politica"],
    anioInicio: 1973,
    anioFin: 1975,
    orden: 9,
  },
  isabel: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1974,
    anioFin: 1976,
    orden: 10,
  },
  macri: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 2015,
    anioFin: 2019,
    numero: 47,
    orden: 15,
  },
  "elecciones-83": {
    epoca: "contemporanea",
    categorias: ["politica", "memoria"],
    anioInicio: 1983,
    anioFin: 1983,
    numero: 48,
    destacada: true,
    orden: 11,
  },
  "de-la-rua": {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1999,
    anioFin: 2001,
    numero: 49,
    orden: 12,
  },
  "juicio-a-las-juntas": {
    epoca: "contemporanea",
    categorias: ["memoria", "politica"],
    anioInicio: 1985,
    anioFin: 1985,
    orden: 13,
  },
  galtieri: {
    epoca: "contemporanea",
    categorias: ["guerras", "memoria"],
    anioInicio: 1981,
    anioFin: 1982,
    orden: 14,
  },
  "alberto-fernandez": {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 2019,
    anioFin: 2023,
    numero: 50,
    orden: 16,
  },
  milei: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 2023,
    anioFin: 2025,
    numero: 51,
    destacada: true,
    orden: 17,
  },
  piqueteros: {
    epoca: "contemporanea",
    categorias: ["sociedad", "politica"],
    anioInicio: 2002,
    anioFin: 2015,
    numero: 52,
    orden: 13,
  },
  conadep: {
    epoca: "contemporanea",
    categorias: ["memoria", "sociedad"],
    anioInicio: 1983,
    anioFin: 1984,
    orden: 15,
  },
  amia: {
    epoca: "contemporanea",
    categorias: ["memoria", "sociedad"],
    anioInicio: 1994,
    anioFin: 1994,
    orden: 16,
  },
  "fabricas-recuperadas": {
    epoca: "contemporanea",
    categorias: ["sociedad", "politica"],
    anioInicio: 2002,
    anioFin: 2015,
    numero: 53,
    orden: 14,
  },
  "la-pandemia": {
    epoca: "contemporanea",
    categorias: ["sociedad", "politica"],
    anioInicio: 2020,
    anioFin: 2021,
    numero: 54,
    orden: 18,
  },
  rodrigazo: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1975,
    anioFin: 1975,
    numero: 55,
    orden: 11,
  },
  walsh: {
    epoca: "contemporanea",
    categorias: ["memoria", "sociedad"],
    anioInicio: 1977,
    anioFin: 1977,
    orden: 17,
  },
  embajada: {
    epoca: "contemporanea",
    categorias: ["memoria", "sociedad"],
    anioInicio: 1992,
    anioFin: 1992,
    orden: 18,
  },
  lanusse: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1971,
    anioFin: 1973,
    numero: 56,
    orden: 10,
  },
  "el-default": {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 2001,
    anioFin: 2001,
    numero: 57,
    orden: 6,
  },
  "revolucion-del-parque": {
    epoca: "moderna",
    categorias: ["politica", "sociedad"],
    anioInicio: 1890,
    anioFin: 1890,
    numero: 58,
    orden: 6,
  },
  erp: {
    epoca: "contemporanea",
    categorias: ["politica", "guerras"],
    anioInicio: 1970,
    anioFin: 1976,
    orden: 9,
  },
  esma: {
    epoca: "contemporanea",
    categorias: ["memoria", "sociedad"],
    anioInicio: 1976,
    anioFin: 1983,
    orden: 8,
  },
  levingston: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1970,
    anioFin: 1971,
    numero: 59,
    orden: 9,
  },
  campora: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1973,
    anioFin: 1973,
    numero: 60,
    orden: 11,
  },
  celman: {
    epoca: "moderna",
    categorias: ["politica", "sociedad"],
    anioInicio: 1886,
    anioFin: 1890,
    numero: 61,
    orden: 5,
  },
  videla: {
    epoca: "contemporanea",
    categorias: ["memoria", "politica"],
    anioInicio: 1976,
    anioFin: 1981,
    orden: 7,
  },
  massera: {
    epoca: "contemporanea",
    categorias: ["memoria", "politica"],
    anioInicio: 1976,
    anioFin: 1978,
    orden: 9,
  },
  "codigo-civil": {
    epoca: "organizacion",
    categorias: ["politica", "sociedad"],
    anioInicio: 1869,
    anioFin: 1871,
    numero: 62,
    orden: 11,
  },
  alsogaray: {
    epoca: "contemporanea",
    categorias: ["politica", "personajes"],
    anioInicio: 1959,
    anioFin: 1999,
    numero: 63,
    orden: 5,
  },
  "ley-de-residencia": {
    epoca: "moderna",
    categorias: ["politica", "sociedad"],
    anioInicio: 1902,
    anioFin: 1902,
    numero: 64,
    orden: 6,
  },
  "plan-austral": {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1985,
    anioFin: 1988,
    numero: 65,
    orden: 7,
  },
  privatizaciones: {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1989,
    anioFin: 1999,
    numero: 66,
    orden: 8,
  },
  "crisis-del-tequila": {
    epoca: "contemporanea",
    categorias: ["politica", "sociedad"],
    anioInicio: 1994,
    anioFin: 1995,
    numero: 67,
    orden: 9,
  },
};
